bundle exec guard
Configuration file: _config.yml
16:05:09 - INFO - Jekyll [33mbuilding... [0m
16:05:09 - INFO - Jekyll [32mbuild completed in 0.81s [0m/home/codio/workspace/Introduction-to-Data-Science/IntroBook â†’ _site
16:05:09 - INFO - Jekyll watching and serving using jekyll at 0.0.0.0:4000/jupyter-book
16:05:09 - INFO - Jekyll watching
16:05:09 - INFO - LiveReload is waiting for a browser to connect.
16:05:09 - INFO - Guard is now watching at '/home/codio/workspace/Introduction-to-Data-Science/IntroBook'
[0G/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/guard-2.14.2/lib/guard/jobs/pry_wrapper.rb:279: warning: method Pry#input_array is deprecated. Use Pry#input_ring instead
[1] guard(main)> Error: Bad file descriptor - read
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:200:in `readline'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:200:in `block in input_readline'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/input_lock.rb:113:in `interruptible_region'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:199:in `input_readline'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:185:in `block in read_line'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:130:in `handle_read_errors'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:171:in `read_line'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:98:in `read'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:68:in `block in repl'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:67:in `loop'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:67:in `repl'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:38:in `block in start'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/input_lock.rb:59:in `__with_ownership'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/input_lock.rb:77:in `with_ownership'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:38:in `start'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:13:in `start'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/pry_class.rb:200:in `start'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/guard-2.14.2/lib/guard/jobs/pry_wrapper.rb:102:in `block (2 levels) in _switch_to_pry'
[1] guard(main)> Error: Bad file descriptor - read
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:200:in `readline'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:200:in `block in input_readline'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/input_lock.rb:113:in `interruptible_region'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:199:in `input_readline'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:185:in `block in read_line'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:130:in `handle_read_errors'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:171:in `read_line'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:98:in `read'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:68:in `block in repl'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:67:in `loop'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:67:in `repl'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:38:in `block in start'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/input_lock.rb:59:in `__with_ownership'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/input_lock.rb:77:in `with_ownership'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:38:in `start'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:13:in `start'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/pry_class.rb:200:in `start'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/guard-2.14.2/lib/guard/jobs/pry_wrapper.rb:102:in `block (2 levels) in _switch_to_pry'
[1] guard(main)> Error: Bad file descriptor - read
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:200:in `readline'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:200:in `block in input_readline'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/input_lock.rb:113:in `interruptible_region'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:199:in `input_readline'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:185:in `block in read_line'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:130:in `handle_read_errors'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:171:in `read_line'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:98:in `read'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:68:in `block in repl'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:67:in `loop'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:67:in `repl'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:38:in `block in start'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/input_lock.rb:59:in `__with_ownership'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/input_lock.rb:77:in `with_ownership'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:38:in `start'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:13:in `start'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/pry_class.rb:200:in `start'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/guard-2.14.2/lib/guard/jobs/pry_wrapper.rb:102:in `block (2 levels) in _switch_to_pry'
[1] guard(main)> Error: Bad file descriptor - read
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:200:in `readline'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:200:in `block in input_readline'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/input_lock.rb:113:in `interruptible_region'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:199:in `input_readline'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:185:in `block in read_line'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:130:in `handle_read_errors'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:171:in `read_line'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:98:in `read'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:68:in `block in repl'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:67:in `loop'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:67:in `repl'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:38:in `block in start'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/input_lock.rb:59:in `__with_ownership'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/input_lock.rb:77:in `with_ownership'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:38:in `start'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:13:in `start'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/pry_class.rb:200:in `start'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/guard-2.14.2/lib/guard/jobs/pry_wrapper.rb:102:in `block (2 levels) in _switch_to_pry'
[1] guard(main)> Error: Bad file descriptor - read
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:200:in `readline'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:200:in `block in input_readline'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/input_lock.rb:113:in `interruptible_region'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:199:in `input_readline'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:185:in `block in read_line'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:130:in `handle_read_errors'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:171:in `read_line'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:98:in `read'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:68:in `block in repl'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:67:in `loop'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:67:in `repl'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:38:in `block in start'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/input_lock.rb:59:in `__with_ownership'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/input_lock.rb:77:in `with_ownership'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:38:in `start'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:13:in `start'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/pry_class.rb:200:in `start'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/guard-2.14.2/lib/guard/jobs/pry_wrapper.rb:102:in `block (2 levels) in _switch_to_pry'
FATAL: Pry failed to get user input using `Readline`.
To fix this you may be able to pass input and output file descriptors to pry directly. e.g.
  Pry.config.input = STDIN
  Pry.config.output = STDOUT
  binding.pry

[0m    Server address: http://0.0.0.0:4000/jupyter-book/
  Server running... press ctrl-c to stop.
]2;

[0m16:05:09 - INFO - Bye bye...
bundle exec guard
Configuration file: _config.yml
16:07:46 - INFO - Jekyll [33mbuilding... [0m
16:07:46 - INFO - Jekyll [32mbuild completed in 0.75s [0m/home/codio/workspace/Introduction-to-Data-Science/IntroBook â†’ _site
16:07:46 - INFO - Jekyll watching and serving using jekyll at 0.0.0.0:4000/jupyter-book
16:07:46 - INFO - Jekyll watching
16:07:46 - INFO - LiveReload is waiting for a browser to connect.
16:07:46 - INFO - Guard is now watching at '/home/codio/workspace/Introduction-to-Data-Science/IntroBook'
[0G/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/guard-2.14.2/lib/guard/jobs/pry_wrapper.rb:279: warning: method Pry#input_array is deprecated. Use Pry#input_ring instead
[1] guard(main)> Error: Bad file descriptor - read
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:200:in `readline'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:200:in `block in input_readline'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/input_lock.rb:113:in `interruptible_region'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:199:in `input_readline'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:185:in `block in read_line'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:130:in `handle_read_errors'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:171:in `read_line'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:98:in `read'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:68:in `block in repl'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:67:in `loop'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:67:in `repl'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:38:in `block in start'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/input_lock.rb:59:in `__with_ownership'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/input_lock.rb:77:in `with_ownership'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:38:in `start'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:13:in `start'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/pry_class.rb:200:in `start'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/guard-2.14.2/lib/guard/jobs/pry_wrapper.rb:102:in `block (2 levels) in _switch_to_pry'
[1] guard(main)> Error: Bad file descriptor - read
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:200:in `readline'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:200:in `block in input_readline'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/input_lock.rb:113:in `interruptible_region'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:199:in `input_readline'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:185:in `block in read_line'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:130:in `handle_read_errors'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:171:in `read_line'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:98:in `read'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:68:in `block in repl'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:67:in `loop'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:67:in `repl'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:38:in `block in start'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/input_lock.rb:59:in `__with_ownership'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/input_lock.rb:77:in `with_ownership'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:38:in `start'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:13:in `start'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/pry_class.rb:200:in `start'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/guard-2.14.2/lib/guard/jobs/pry_wrapper.rb:102:in `block (2 levels) in _switch_to_pry'
[1] guard(main)> Error: Bad file descriptor - read
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:200:in `readline'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:200:in `block in input_readline'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/input_lock.rb:113:in `interruptible_region'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:199:in `input_readline'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:185:in `block in read_line'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:130:in `handle_read_errors'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:171:in `read_line'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:98:in `read'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:68:in `block in repl'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:67:in `loop'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:67:in `repl'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:38:in `block in start'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/input_lock.rb:59:in `__with_ownership'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/input_lock.rb:77:in `with_ownership'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:38:in `start'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:13:in `start'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/pry_class.rb:200:in `start'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/guard-2.14.2/lib/guard/jobs/pry_wrapper.rb:102:in `block (2 levels) in _switch_to_pry'
[1] guard(main)> Error: Bad file descriptor - read
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:200:in `readline'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:200:in `block in input_readline'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/input_lock.rb:113:in `interruptible_region'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:199:in `input_readline'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:185:in `block in read_line'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:130:in `handle_read_errors'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:171:in `read_line'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:98:in `read'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:68:in `block in repl'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:67:in `loop'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:67:in `repl'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:38:in `block in start'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/input_lock.rb:59:in `__with_ownership'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/input_lock.rb:77:in `with_ownership'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:38:in `start'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:13:in `start'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/pry_class.rb:200:in `start'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/guard-2.14.2/lib/guard/jobs/pry_wrapper.rb:102:in `block (2 levels) in _switch_to_pry'
[1] guard(main)> Error: Bad file descriptor - read
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:200:in `readline'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:200:in `block in input_readline'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/input_lock.rb:113:in `interruptible_region'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:199:in `input_readline'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:185:in `block in read_line'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:130:in `handle_read_errors'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:171:in `read_line'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:98:in `read'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:68:in `block in repl'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:67:in `loop'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:67:in `repl'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:38:in `block in start'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/input_lock.rb:59:in `__with_ownership'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/input_lock.rb:77:in `with_ownership'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:38:in `start'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:13:in `start'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/pry_class.rb:200:in `start'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/guard-2.14.2/lib/guard/jobs/pry_wrapper.rb:102:in `block (2 levels) in _switch_to_pry'
FATAL: Pry failed to get user input using `Readline`.
To fix this you may be able to pass input and output file descriptors to pry directly. e.g.
  Pry.config.input = STDIN
  Pry.config.output = STDOUT
  binding.pry

[0m    Server address: http://0.0.0.0:4000/jupyter-book/
  Server running... press ctrl-c to stop.
E, [2019-11-14T16:07:46.936924 #2178] ERROR -- : run() in thread failed: closed stream:\n /home/codio/anaconda/lib/ruby/gems/2.6.0/gems/rb-inotify-0.10.0/lib/rb-inotify/notifier.rb:44:in `fileno'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/rb-inotify-0.10.0/lib/rb-inotify/notifier.rb:44:in `fd'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/rb-inotify-0.10.0/lib/rb-inotify/notifier.rb:275:in `read_events'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/rb-inotify-0.10.0/lib/rb-inotify/notifier.rb:252:in `process'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/rb-inotify-0.10.0/lib/rb-inotify/notifier.rb:229:in `block in run'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/rb-inotify-0.10.0/lib/rb-inotify/notifier.rb:226:in `synchronize'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/rb-inotify-0.10.0/lib/rb-inotify/notifier.rb:226:in `run'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/listen-3.1.5/lib/listen/adapter/linux.rb:39:in `_run'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/listen-3.1.5/lib/listen/adapter/base.rb:78:in `block in start'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/listen-3.1.5/lib/listen/internals/thread_pool.rb:6:in `block in add'\n\ncalled from:\n /home/codio/anaconda/lib/ruby/2.6.0/forwardable.rb:230:in `start'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/listen-3.1.5/lib/listen/listener.rb:68:in `block in <class:Listener>'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/listen-3.1.5/lib/listen/fsm.rb:121:in `instance_eval'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/listen-3.1.5/lib/listen/fsm.rb:121:in `call'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/listen-3.1.5/lib/listen/fsm.rb:91:in `transition_with_callbacks!'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/listen-3.1.5/lib/listen/fsm.rb:57:in `transition'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/listen-3.1.5/lib/listen/listener.rb:91:in `start'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/guard-2.14.2/lib/guard/commander.rb:35:in `start'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/guard-2.14.2/lib/guard/cli/environments/valid.rb:16:in `start_guard'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/guard-2.14.2/lib/guard/cli.rb:122:in `start'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/guard-2.14.2/lib/guard/aruba_adapter.rb:32:in `execute'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/guard-2.14.2/lib/guard/aruba_adapter.rb:19:in `execute!'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/guard-2.14.2/bin/_guard-core:11:in `<main>'
#<Thread:0x000055a178020890@/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/listen-3.1.5/lib/listen/internals/thread_pool.rb:6 run> terminated with exception (report_on_exception is true):
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/rb-inotify-0.10.0/lib/rb-inotify/notifier.rb:44:in `fileno': closed stream (IOError)
	from /home/codio/anaconda/lib/ruby/gems/2.6.0/gems/rb-inotify-0.10.0/lib/rb-inotify/notifier.rb:44:in `fd'
	from /home/codio/anaconda/lib/ruby/gems/2.6.0/gems/rb-inotify-0.10.0/lib/rb-inotify/notifier.rb:275:in `read_events'
	from /home/codio/anaconda/lib/ruby/gems/2.6.0/gems/rb-inotify-0.10.0/lib/rb-inotify/notifier.rb:252:in `process'
	from /home/codio/anaconda/lib/ruby/gems/2.6.0/gems/rb-inotify-0.10.0/lib/rb-inotify/notifier.rb:229:in `block in run'
	from /home/codio/anaconda/lib/ruby/gems/2.6.0/gems/rb-inotify-0.10.0/lib/rb-inotify/notifier.rb:226:in `synchronize'
	from /home/codio/anaconda/lib/ruby/gems/2.6.0/gems/rb-inotify-0.10.0/lib/rb-inotify/notifier.rb:226:in `run'
	from /home/codio/anaconda/lib/ruby/gems/2.6.0/gems/listen-3.1.5/lib/listen/adapter/linux.rb:39:in `_run'
	from /home/codio/anaconda/lib/ruby/gems/2.6.0/gems/listen-3.1.5/lib/listen/adapter/base.rb:78:in `block in start'
	from /home/codio/anaconda/lib/ruby/gems/2.6.0/gems/listen-3.1.5/lib/listen/internals/thread_pool.rb:6:in `block in add'
]2;

[0m16:07:46 - INFO - Bye bye...
bundle exec guard
Configuration file: _config.yml
16:07:52 - INFO - Jekyll [33mbuilding... [0m
16:07:53 - INFO - Jekyll [32mbuild completed in 0.78s [0m/home/codio/workspace/Introduction-to-Data-Science/IntroBook â†’ _site
16:07:53 - INFO - Jekyll watching and serving using jekyll at 0.0.0.0:4000/jupyter-book
16:07:53 - INFO - Jekyll watching
16:07:53 - INFO - LiveReload is waiting for a browser to connect.
16:07:53 - INFO - Guard is now watching at '/home/codio/workspace/Introduction-to-Data-Science/IntroBook'
[0G/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/guard-2.14.2/lib/guard/jobs/pry_wrapper.rb:279: warning: method Pry#input_array is deprecated. Use Pry#input_ring instead
[1] guard(main)> Error: Bad file descriptor - read
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:200:in `readline'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:200:in `block in input_readline'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/input_lock.rb:113:in `interruptible_region'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:199:in `input_readline'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:185:in `block in read_line'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:130:in `handle_read_errors'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:171:in `read_line'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:98:in `read'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:68:in `block in repl'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:67:in `loop'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:67:in `repl'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:38:in `block in start'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/input_lock.rb:59:in `__with_ownership'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/input_lock.rb:77:in `with_ownership'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:38:in `start'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:13:in `start'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/pry_class.rb:200:in `start'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/guard-2.14.2/lib/guard/jobs/pry_wrapper.rb:102:in `block (2 levels) in _switch_to_pry'
[1] guard(main)> Error: Bad file descriptor - read
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:200:in `readline'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:200:in `block in input_readline'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/input_lock.rb:113:in `interruptible_region'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:199:in `input_readline'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:185:in `block in read_line'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:130:in `handle_read_errors'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:171:in `read_line'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:98:in `read'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:68:in `block in repl'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:67:in `loop'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:67:in `repl'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:38:in `block in start'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/input_lock.rb:59:in `__with_ownership'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/input_lock.rb:77:in `with_ownership'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:38:in `start'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:13:in `start'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/pry_class.rb:200:in `start'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/guard-2.14.2/lib/guard/jobs/pry_wrapper.rb:102:in `block (2 levels) in _switch_to_pry'
[1] guard(main)> Error: Bad file descriptor - read
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:200:in `readline'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:200:in `block in input_readline'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/input_lock.rb:113:in `interruptible_region'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:199:in `input_readline'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:185:in `block in read_line'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:130:in `handle_read_errors'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:171:in `read_line'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:98:in `read'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:68:in `block in repl'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:67:in `loop'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:67:in `repl'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:38:in `block in start'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/input_lock.rb:59:in `__with_ownership'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/input_lock.rb:77:in `with_ownership'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:38:in `start'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:13:in `start'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/pry_class.rb:200:in `start'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/guard-2.14.2/lib/guard/jobs/pry_wrapper.rb:102:in `block (2 levels) in _switch_to_pry'
[1] guard(main)> Error: Bad file descriptor - read
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:200:in `readline'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:200:in `block in input_readline'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/input_lock.rb:113:in `interruptible_region'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:199:in `input_readline'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:185:in `block in read_line'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:130:in `handle_read_errors'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:171:in `read_line'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:98:in `read'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:68:in `block in repl'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:67:in `loop'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:67:in `repl'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:38:in `block in start'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/input_lock.rb:59:in `__with_ownership'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/input_lock.rb:77:in `with_ownership'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:38:in `start'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:13:in `start'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/pry_class.rb:200:in `start'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/guard-2.14.2/lib/guard/jobs/pry_wrapper.rb:102:in `block (2 levels) in _switch_to_pry'
[1] guard(main)> Error: Bad file descriptor - read
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:200:in `readline'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:200:in `block in input_readline'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/input_lock.rb:113:in `interruptible_region'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:199:in `input_readline'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:185:in `block in read_line'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:130:in `handle_read_errors'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:171:in `read_line'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:98:in `read'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:68:in `block in repl'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:67:in `loop'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:67:in `repl'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:38:in `block in start'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/input_lock.rb:59:in `__with_ownership'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/input_lock.rb:77:in `with_ownership'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:38:in `start'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:13:in `start'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/pry_class.rb:200:in `start'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/guard-2.14.2/lib/guard/jobs/pry_wrapper.rb:102:in `block (2 levels) in _switch_to_pry'
FATAL: Pry failed to get user input using `Readline`.
To fix this you may be able to pass input and output file descriptors to pry directly. e.g.
  Pry.config.input = STDIN
  Pry.config.output = STDOUT
  binding.pry

[0m    Server address: http://0.0.0.0:4000/jupyter-book/
  Server running... press ctrl-c to stop.
E, [2019-11-14T16:07:53.112465 #2190] ERROR -- : run() in thread failed: closed stream:\n /home/codio/anaconda/lib/ruby/gems/2.6.0/gems/rb-inotify-0.10.0/lib/rb-inotify/notifier.rb:44:in `fileno'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/rb-inotify-0.10.0/lib/rb-inotify/notifier.rb:44:in `fd'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/rb-inotify-0.10.0/lib/rb-inotify/notifier.rb:275:in `read_events'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/rb-inotify-0.10.0/lib/rb-inotify/notifier.rb:252:in `process'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/rb-inotify-0.10.0/lib/rb-inotify/notifier.rb:229:in `block in run'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/rb-inotify-0.10.0/lib/rb-inotify/notifier.rb:226:in `synchronize'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/rb-inotify-0.10.0/lib/rb-inotify/notifier.rb:226:in `run'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/listen-3.1.5/lib/listen/adapter/linux.rb:39:in `_run'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/listen-3.1.5/lib/listen/adapter/base.rb:78:in `block in start'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/listen-3.1.5/lib/listen/internals/thread_pool.rb:6:in `block in add'\n\ncalled from:\n /home/codio/anaconda/lib/ruby/2.6.0/forwardable.rb:230:in `start'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/listen-3.1.5/lib/listen/listener.rb:68:in `block in <class:Listener>'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/listen-3.1.5/lib/listen/fsm.rb:121:in `instance_eval'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/listen-3.1.5/lib/listen/fsm.rb:121:in `call'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/listen-3.1.5/lib/listen/fsm.rb:91:in `transition_with_callbacks!'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/listen-3.1.5/lib/listen/fsm.rb:57:in `transition'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/listen-3.1.5/lib/listen/listener.rb:91:in `start'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/guard-2.14.2/lib/guard/commander.rb:35:in `start'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/guard-2.14.2/lib/guard/cli/environments/valid.rb:16:in `start_guard'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/guard-2.14.2/lib/guard/cli.rb:122:in `start'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/guard-2.14.2/lib/guard/aruba_adapter.rb:32:in `execute'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/guard-2.14.2/lib/guard/aruba_adapter.rb:19:in `execute!'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/guard-2.14.2/bin/_guard-core:11:in `<main>'
#<Thread:0x0000556814a917e0@/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/listen-3.1.5/lib/listen/internals/thread_pool.rb:6 run> terminated with exception (report_on_exception is true):
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/rb-inotify-0.10.0/lib/rb-inotify/notifier.rb:44:in `fileno': closed stream (IOError)
	from /home/codio/anaconda/lib/ruby/gems/2.6.0/gems/rb-inotify-0.10.0/lib/rb-inotify/notifier.rb:44:in `fd'
	from /home/codio/anaconda/lib/ruby/gems/2.6.0/gems/rb-inotify-0.10.0/lib/rb-inotify/notifier.rb:275:in `read_events'
	from /home/codio/anaconda/lib/ruby/gems/2.6.0/gems/rb-inotify-0.10.0/lib/rb-inotify/notifier.rb:252:in `process'
	from /home/codio/anaconda/lib/ruby/gems/2.6.0/gems/rb-inotify-0.10.0/lib/rb-inotify/notifier.rb:229:in `block in run'
	from /home/codio/anaconda/lib/ruby/gems/2.6.0/gems/rb-inotify-0.10.0/lib/rb-inotify/notifier.rb:226:in `synchronize'
	from /home/codio/anaconda/lib/ruby/gems/2.6.0/gems/rb-inotify-0.10.0/lib/rb-inotify/notifier.rb:226:in `run'
	from /home/codio/anaconda/lib/ruby/gems/2.6.0/gems/listen-3.1.5/lib/listen/adapter/linux.rb:39:in `_run'
	from /home/codio/anaconda/lib/ruby/gems/2.6.0/gems/listen-3.1.5/lib/listen/adapter/base.rb:78:in `block in start'
	from /home/codio/anaconda/lib/ruby/gems/2.6.0/gems/listen-3.1.5/lib/listen/internals/thread_pool.rb:6:in `block in add'
]2;

[0m16:07:53 - INFO - Bye bye...
bundle exec guard
Configuration file: _config.yml
14:47:49 - INFO - Jekyll [33mbuilding... [0m
14:47:50 - INFO - Jekyll [32mbuild completed in 0.81s [0m/home/codio/workspace/Introduction-to-Data-Science/IntroBook â†’ _site
14:47:50 - INFO - Jekyll watching and serving using jekyll at 0.0.0.0:4000/jupyter-book
14:47:50 - INFO - Jekyll watching
14:47:50 - INFO - LiveReload is waiting for a browser to connect.
14:47:50 - INFO - Guard is now watching at '/home/codio/workspace/Introduction-to-Data-Science/IntroBook'
[0G/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/guard-2.14.2/lib/guard/jobs/pry_wrapper.rb:279: warning: method Pry#input_array is deprecated. Use Pry#input_ring instead
[1] guard(main)> Error: Bad file descriptor - read
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:200:in `readline'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:200:in `block in input_readline'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/input_lock.rb:113:in `interruptible_region'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:199:in `input_readline'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:185:in `block in read_line'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:130:in `handle_read_errors'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:171:in `read_line'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:98:in `read'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:68:in `block in repl'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:67:in `loop'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:67:in `repl'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:38:in `block in start'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/input_lock.rb:59:in `__with_ownership'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/input_lock.rb:77:in `with_ownership'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:38:in `start'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:13:in `start'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/pry_class.rb:200:in `start'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/guard-2.14.2/lib/guard/jobs/pry_wrapper.rb:102:in `block (2 levels) in _switch_to_pry'
[1] guard(main)> Error: Bad file descriptor - read
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:200:in `readline'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:200:in `block in input_readline'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/input_lock.rb:113:in `interruptible_region'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:199:in `input_readline'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:185:in `block in read_line'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:130:in `handle_read_errors'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:171:in `read_line'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:98:in `read'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:68:in `block in repl'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:67:in `loop'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:67:in `repl'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:38:in `block in start'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/input_lock.rb:59:in `__with_ownership'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/input_lock.rb:77:in `with_ownership'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:38:in `start'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:13:in `start'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/pry_class.rb:200:in `start'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/guard-2.14.2/lib/guard/jobs/pry_wrapper.rb:102:in `block (2 levels) in _switch_to_pry'
[1] guard(main)> Error: Bad file descriptor - read
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:200:in `readline'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:200:in `block in input_readline'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/input_lock.rb:113:in `interruptible_region'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:199:in `input_readline'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:185:in `block in read_line'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:130:in `handle_read_errors'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:171:in `read_line'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:98:in `read'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:68:in `block in repl'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:67:in `loop'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:67:in `repl'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:38:in `block in start'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/input_lock.rb:59:in `__with_ownership'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/input_lock.rb:77:in `with_ownership'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:38:in `start'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:13:in `start'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/pry_class.rb:200:in `start'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/guard-2.14.2/lib/guard/jobs/pry_wrapper.rb:102:in `block (2 levels) in _switch_to_pry'
[1] guard(main)> Error: Bad file descriptor - read
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:200:in `readline'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:200:in `block in input_readline'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/input_lock.rb:113:in `interruptible_region'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:199:in `input_readline'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:185:in `block in read_line'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:130:in `handle_read_errors'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:171:in `read_line'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:98:in `read'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:68:in `block in repl'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:67:in `loop'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:67:in `repl'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:38:in `block in start'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/input_lock.rb:59:in `__with_ownership'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/input_lock.rb:77:in `with_ownership'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:38:in `start'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:13:in `start'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/pry_class.rb:200:in `start'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/guard-2.14.2/lib/guard/jobs/pry_wrapper.rb:102:in `block (2 levels) in _switch_to_pry'
[1] guard(main)> Error: Bad file descriptor - read
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:200:in `readline'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:200:in `block in input_readline'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/input_lock.rb:113:in `interruptible_region'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:199:in `input_readline'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:185:in `block in read_line'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:130:in `handle_read_errors'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:171:in `read_line'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:98:in `read'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:68:in `block in repl'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:67:in `loop'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:67:in `repl'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:38:in `block in start'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/input_lock.rb:59:in `__with_ownership'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/input_lock.rb:77:in `with_ownership'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:38:in `start'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:13:in `start'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/pry_class.rb:200:in `start'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/guard-2.14.2/lib/guard/jobs/pry_wrapper.rb:102:in `block (2 levels) in _switch_to_pry'
FATAL: Pry failed to get user input using `Readline`.
To fix this you may be able to pass input and output file descriptors to pry directly. e.g.
  Pry.config.input = STDIN
  Pry.config.output = STDOUT
  binding.pry

[0m    Server address: http://0.0.0.0:4000/jupyter-book/
  Server running... press ctrl-c to stop.
]2;

[0m14:47:50 - INFO - Bye bye...
bundle exec guard
Configuration file: _config.yml
15:08:41 - INFO - Jekyll [33mbuilding... [0m
15:08:42 - INFO - Jekyll [32mbuild completed in 0.87s [0m/home/codio/workspace/Introduction-to-Data-Science/IntroBook â†’ _site
15:08:42 - INFO - Jekyll watching and serving using jekyll at 0.0.0.0:4000/jupyter-book
15:08:42 - INFO - Jekyll watching
15:08:42 - INFO - LiveReload is waiting for a browser to connect.
15:08:42 - INFO - Guard is now watching at '/home/codio/workspace/Introduction-to-Data-Science/IntroBook'
[0G/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/guard-2.14.2/lib/guard/jobs/pry_wrapper.rb:279: warning: method Pry#input_array is deprecated. Use Pry#input_ring instead
[1] guard(main)> Error: Bad file descriptor - read
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:200:in `readline'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:200:in `block in input_readline'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/input_lock.rb:113:in `interruptible_region'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:199:in `input_readline'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:185:in `block in read_line'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:130:in `handle_read_errors'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:171:in `read_line'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:98:in `read'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:68:in `block in repl'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:67:in `loop'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:67:in `repl'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:38:in `block in start'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/input_lock.rb:59:in `__with_ownership'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/input_lock.rb:77:in `with_ownership'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:38:in `start'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:13:in `start'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/pry_class.rb:200:in `start'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/guard-2.14.2/lib/guard/jobs/pry_wrapper.rb:102:in `block (2 levels) in _switch_to_pry'
[1] guard(main)> Error: Bad file descriptor - read
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:200:in `readline'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:200:in `block in input_readline'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/input_lock.rb:113:in `interruptible_region'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:199:in `input_readline'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:185:in `block in read_line'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:130:in `handle_read_errors'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:171:in `read_line'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:98:in `read'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:68:in `block in repl'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:67:in `loop'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:67:in `repl'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:38:in `block in start'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/input_lock.rb:59:in `__with_ownership'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/input_lock.rb:77:in `with_ownership'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:38:in `start'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:13:in `start'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/pry_class.rb:200:in `start'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/guard-2.14.2/lib/guard/jobs/pry_wrapper.rb:102:in `block (2 levels) in _switch_to_pry'
[1] guard(main)> Error: Bad file descriptor - read
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:200:in `readline'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:200:in `block in input_readline'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/input_lock.rb:113:in `interruptible_region'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:199:in `input_readline'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:185:in `block in read_line'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:130:in `handle_read_errors'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:171:in `read_line'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:98:in `read'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:68:in `block in repl'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:67:in `loop'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:67:in `repl'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:38:in `block in start'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/input_lock.rb:59:in `__with_ownership'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/input_lock.rb:77:in `with_ownership'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:38:in `start'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:13:in `start'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/pry_class.rb:200:in `start'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/guard-2.14.2/lib/guard/jobs/pry_wrapper.rb:102:in `block (2 levels) in _switch_to_pry'
[1] guard(main)> Error: Bad file descriptor - read
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:200:in `readline'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:200:in `block in input_readline'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/input_lock.rb:113:in `interruptible_region'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:199:in `input_readline'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:185:in `block in read_line'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:130:in `handle_read_errors'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:171:in `read_line'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:98:in `read'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:68:in `block in repl'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:67:in `loop'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:67:in `repl'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:38:in `block in start'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/input_lock.rb:59:in `__with_ownership'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/input_lock.rb:77:in `with_ownership'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:38:in `start'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:13:in `start'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/pry_class.rb:200:in `start'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/guard-2.14.2/lib/guard/jobs/pry_wrapper.rb:102:in `block (2 levels) in _switch_to_pry'
[1] guard(main)> Error: Bad file descriptor - read
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:200:in `readline'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:200:in `block in input_readline'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/input_lock.rb:113:in `interruptible_region'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:199:in `input_readline'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:185:in `block in read_line'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:130:in `handle_read_errors'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:171:in `read_line'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:98:in `read'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:68:in `block in repl'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:67:in `loop'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:67:in `repl'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:38:in `block in start'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/input_lock.rb:59:in `__with_ownership'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/input_lock.rb:77:in `with_ownership'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:38:in `start'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:13:in `start'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/pry_class.rb:200:in `start'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/guard-2.14.2/lib/guard/jobs/pry_wrapper.rb:102:in `block (2 levels) in _switch_to_pry'
FATAL: Pry failed to get user input using `Readline`.
To fix this you may be able to pass input and output file descriptors to pry directly. e.g.
  Pry.config.input = STDIN
  Pry.config.output = STDOUT
  binding.pry

[0m/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/guard-2.14.2/lib/guard/jobs/pry_wrapper.rb:90:in `handle_interrupt': Interrupt (Interrupt)
	from /home/codio/anaconda/lib/ruby/2.6.0/forwardable.rb:230:in `handle_interrupt'
	from /home/codio/anaconda/lib/ruby/gems/2.6.0/gems/guard-2.14.2/lib/guard.rb:68:in `block in setup'
	from /home/codio/anaconda/lib/ruby/2.6.0/webrick/httputils.rb:116:in `block (2 levels) in load_mime_types'
	from /home/codio/anaconda/lib/ruby/2.6.0/webrick/httputils.rb:115:in `each'
	from /home/codio/anaconda/lib/ruby/2.6.0/webrick/httputils.rb:115:in `block in load_mime_types'
	from /home/codio/anaconda/lib/ruby/2.6.0/open-uri.rb:37:in `open'
	from /home/codio/anaconda/lib/ruby/2.6.0/open-uri.rb:37:in `open'
	from /home/codio/anaconda/lib/ruby/2.6.0/webrick/httputils.rb:113:in `load_mime_types'
	from /home/codio/anaconda/lib/ruby/gems/2.6.0/gems/jekyll-3.8.5/lib/jekyll/commands/serve.rb:378:in `mime_types'
	from /home/codio/anaconda/lib/ruby/gems/2.6.0/gems/jekyll-3.8.5/lib/jekyll/commands/serve.rb:204:in `webrick_opts'
	from /home/codio/anaconda/lib/ruby/gems/2.6.0/gems/jekyll-3.8.5/lib/jekyll/commands/serve.rb:228:in `start_up_webrick'
	from /home/codio/anaconda/lib/ruby/gems/2.6.0/gems/jekyll-3.8.5/lib/jekyll/commands/serve.rb:104:in `process'
	from /home/codio/anaconda/lib/ruby/gems/2.6.0/gems/guard-jekyll-plus-2.0.2/lib/guard/jekyll_plus/server.rb:69:in `block in start_jekyll'
	from /home/codio/anaconda/lib/ruby/gems/2.6.0/gems/guard-jekyll-plus-2.0.2/lib/guard/jekyll_plus/server.rb:68:in `fork'
	from /home/codio/anaconda/lib/ruby/gems/2.6.0/gems/guard-jekyll-plus-2.0.2/lib/guard/jekyll_plus/server.rb:68:in `start_jekyll'
	from /home/codio/anaconda/lib/ruby/gems/2.6.0/gems/guard-jekyll-plus-2.0.2/lib/guard/jekyll_plus/server.rb:18:in `start'
	from /home/codio/anaconda/lib/ruby/gems/2.6.0/gems/guard-jekyll-plus-2.0.2/lib/guard/jekyll_plus.rb:25:in `start'
	from /home/codio/anaconda/lib/ruby/gems/2.6.0/gems/guard-2.14.2/lib/guard/runner.rb:83:in `block (2 levels) in _supervise'
	from /home/codio/anaconda/lib/ruby/gems/2.6.0/gems/guard-2.14.2/lib/guard/ui/config.rb:62:in `block in with_progname'
	from /home/codio/anaconda/lib/ruby/gems/2.6.0/gems/lumberjack-1.0.13/lib/lumberjack/logger.rb:271:in `push_thread_local_value'
	from /home/codio/anaconda/lib/ruby/gems/2.6.0/gems/lumberjack-1.0.13/lib/lumberjack/logger.rb:232:in `set_progname'
	from /home/codio/anaconda/lib/ruby/gems/2.6.0/gems/guard-2.14.2/lib/guard/ui/config.rb:61:in `with_progname'
	from /home/codio/anaconda/lib/ruby/gems/2.6.0/gems/guard-2.14.2/lib/guard/runner.rb:81:in `block in _supervise'
	from /home/codio/anaconda/lib/ruby/gems/2.6.0/gems/guard-2.14.2/lib/guard/runner.rb:79:in `catch'
	from /home/codio/anaconda/lib/ruby/gems/2.6.0/gems/guard-2.14.2/lib/guard/runner.rb:79:in `_supervise'
	from /home/codio/anaconda/lib/ruby/gems/2.6.0/gems/guard-2.14.2/lib/guard/runner.rb:22:in `block (3 levels) in run'
	from /home/codio/anaconda/lib/ruby/gems/2.6.0/gems/guard-2.14.2/lib/guard/runner.rb:121:in `block (2 levels) in _run_group_plugins'
	from /home/codio/anaconda/lib/ruby/gems/2.6.0/gems/guard-2.14.2/lib/guard/runner.rb:119:in `each'
	from /home/codio/anaconda/lib/ruby/gems/2.6.0/gems/guard-2.14.2/lib/guard/runner.rb:119:in `block in _run_group_plugins'
	from /home/codio/anaconda/lib/ruby/gems/2.6.0/gems/guard-2.14.2/lib/guard/runner.rb:118:in `catch'
	from /home/codio/anaconda/lib/ruby/gems/2.6.0/gems/guard-2.14.2/lib/guard/runner.rb:118:in `_run_group_plugins'
	from /home/codio/anaconda/lib/ruby/gems/2.6.0/gems/guard-2.14.2/lib/guard/runner.rb:21:in `block (2 levels) in run'
	from /home/codio/anaconda/lib/ruby/gems/2.6.0/gems/guard-2.14.2/lib/guard/runner.rb:20:in `each'
	from /home/codio/anaconda/lib/ruby/gems/2.6.0/gems/guard-2.14.2/lib/guard/runner.rb:20:in `block in run'
	from /home/codio/anaconda/lib/ruby/gems/2.6.0/gems/lumberjack-1.0.13/lib/lumberjack.rb:34:in `unit_of_work'
	from /home/codio/anaconda/lib/ruby/gems/2.6.0/gems/guard-2.14.2/lib/guard/runner.rb:18:in `run'
	from /home/codio/anaconda/lib/ruby/gems/2.6.0/gems/guard-2.14.2/lib/guard/commander.rb:34:in `start'
	from /home/codio/anaconda/lib/ruby/gems/2.6.0/gems/guard-2.14.2/lib/guard/cli/environments/valid.rb:16:in `start_guard'
	from /home/codio/anaconda/lib/ruby/gems/2.6.0/gems/guard-2.14.2/lib/guard/cli.rb:122:in `start'
	from /home/codio/anaconda/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /home/codio/anaconda/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /home/codio/anaconda/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /home/codio/anaconda/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /home/codio/anaconda/lib/ruby/gems/2.6.0/gems/guard-2.14.2/lib/guard/aruba_adapter.rb:32:in `execute'
	from /home/codio/anaconda/lib/ruby/gems/2.6.0/gems/guard-2.14.2/lib/guard/aruba_adapter.rb:19:in `execute!'
	from /home/codio/anaconda/lib/ruby/gems/2.6.0/gems/guard-2.14.2/bin/_guard-core:11:in `<main>'
]2;

[0m15:08:42 - INFO - Bye bye...
bundle exec guard
Configuration file: _config.yml
15:09:03 - INFO - Jekyll [33mbuilding... [0m
15:09:04 - INFO - Jekyll [32mbuild completed in 0.76s [0m/home/codio/workspace/Introduction-to-Data-Science/IntroBook â†’ _site
15:09:04 - INFO - Jekyll watching and serving using jekyll at 0.0.0.0:4000/jupyter-book
15:09:04 - INFO - Jekyll watching
15:09:04 - INFO - LiveReload is waiting for a browser to connect.
15:09:04 - INFO - Guard is now watching at '/home/codio/workspace/Introduction-to-Data-Science/IntroBook'
[0G/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/guard-2.14.2/lib/guard/jobs/pry_wrapper.rb:279: warning: method Pry#input_array is deprecated. Use Pry#input_ring instead
[1] guard(main)> Error: Bad file descriptor - read
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:200:in `readline'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:200:in `block in input_readline'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/input_lock.rb:113:in `interruptible_region'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:199:in `input_readline'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:185:in `block in read_line'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:130:in `handle_read_errors'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:171:in `read_line'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:98:in `read'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:68:in `block in repl'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:67:in `loop'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:67:in `repl'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:38:in `block in start'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/input_lock.rb:59:in `__with_ownership'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/input_lock.rb:77:in `with_ownership'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:38:in `start'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:13:in `start'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/pry_class.rb:200:in `start'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/guard-2.14.2/lib/guard/jobs/pry_wrapper.rb:102:in `block (2 levels) in _switch_to_pry'
[1] guard(main)> Error: Bad file descriptor - read
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:200:in `readline'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:200:in `block in input_readline'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/input_lock.rb:113:in `interruptible_region'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:199:in `input_readline'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:185:in `block in read_line'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:130:in `handle_read_errors'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:171:in `read_line'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:98:in `read'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:68:in `block in repl'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:67:in `loop'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:67:in `repl'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:38:in `block in start'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/input_lock.rb:59:in `__with_ownership'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/input_lock.rb:77:in `with_ownership'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:38:in `start'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:13:in `start'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/pry_class.rb:200:in `start'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/guard-2.14.2/lib/guard/jobs/pry_wrapper.rb:102:in `block (2 levels) in _switch_to_pry'
[1] guard(main)> Error: Bad file descriptor - read
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:200:in `readline'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:200:in `block in input_readline'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/input_lock.rb:113:in `interruptible_region'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:199:in `input_readline'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:185:in `block in read_line'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:130:in `handle_read_errors'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:171:in `read_line'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:98:in `read'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:68:in `block in repl'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:67:in `loop'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:67:in `repl'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:38:in `block in start'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/input_lock.rb:59:in `__with_ownership'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/input_lock.rb:77:in `with_ownership'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:38:in `start'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:13:in `start'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/pry_class.rb:200:in `start'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/guard-2.14.2/lib/guard/jobs/pry_wrapper.rb:102:in `block (2 levels) in _switch_to_pry'
[1] guard(main)> Error: Bad file descriptor - read
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:200:in `readline'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:200:in `block in input_readline'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/input_lock.rb:113:in `interruptible_region'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:199:in `input_readline'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:185:in `block in read_line'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:130:in `handle_read_errors'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:171:in `read_line'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:98:in `read'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:68:in `block in repl'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:67:in `loop'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:67:in `repl'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:38:in `block in start'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/input_lock.rb:59:in `__with_ownership'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/input_lock.rb:77:in `with_ownership'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:38:in `start'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:13:in `start'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/pry_class.rb:200:in `start'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/guard-2.14.2/lib/guard/jobs/pry_wrapper.rb:102:in `block (2 levels) in _switch_to_pry'
[1] guard(main)> Error: Bad file descriptor - read
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:200:in `readline'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:200:in `block in input_readline'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/input_lock.rb:113:in `interruptible_region'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:199:in `input_readline'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:185:in `block in read_line'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:130:in `handle_read_errors'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:171:in `read_line'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:98:in `read'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:68:in `block in repl'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:67:in `loop'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:67:in `repl'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:38:in `block in start'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/input_lock.rb:59:in `__with_ownership'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/input_lock.rb:77:in `with_ownership'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:38:in `start'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:13:in `start'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/pry_class.rb:200:in `start'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/guard-2.14.2/lib/guard/jobs/pry_wrapper.rb:102:in `block (2 levels) in _switch_to_pry'
FATAL: Pry failed to get user input using `Readline`.
To fix this you may be able to pass input and output file descriptors to pry directly. e.g.
  Pry.config.input = STDIN
  Pry.config.output = STDOUT
  binding.pry

[0m/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/guard-2.14.2/lib/guard/jobs/pry_wrapper.rb:90:in `handle_interrupt': Interrupt (Interrupt)
	from /home/codio/anaconda/lib/ruby/2.6.0/forwardable.rb:230:in `handle_interrupt'
	from /home/codio/anaconda/lib/ruby/gems/2.6.0/gems/guard-2.14.2/lib/guard.rb:68:in `block in setup'
	from /home/codio/anaconda/lib/ruby/2.6.0/webrick/httputils.rb:118:in `split'
	from /home/codio/anaconda/lib/ruby/2.6.0/webrick/httputils.rb:118:in `block (2 levels) in load_mime_types'
	from /home/codio/anaconda/lib/ruby/2.6.0/webrick/httputils.rb:115:in `each'
	from /home/codio/anaconda/lib/ruby/2.6.0/webrick/httputils.rb:115:in `block in load_mime_types'
	from /home/codio/anaconda/lib/ruby/2.6.0/open-uri.rb:37:in `open'
	from /home/codio/anaconda/lib/ruby/2.6.0/open-uri.rb:37:in `open'
	from /home/codio/anaconda/lib/ruby/2.6.0/webrick/httputils.rb:113:in `load_mime_types'
	from /home/codio/anaconda/lib/ruby/gems/2.6.0/gems/jekyll-3.8.5/lib/jekyll/commands/serve.rb:378:in `mime_types'
	from /home/codio/anaconda/lib/ruby/gems/2.6.0/gems/jekyll-3.8.5/lib/jekyll/commands/serve.rb:204:in `webrick_opts'
	from /home/codio/anaconda/lib/ruby/gems/2.6.0/gems/jekyll-3.8.5/lib/jekyll/commands/serve.rb:228:in `start_up_webrick'
	from /home/codio/anaconda/lib/ruby/gems/2.6.0/gems/jekyll-3.8.5/lib/jekyll/commands/serve.rb:104:in `process'
	from /home/codio/anaconda/lib/ruby/gems/2.6.0/gems/guard-jekyll-plus-2.0.2/lib/guard/jekyll_plus/server.rb:69:in `block in start_jekyll'
	from /home/codio/anaconda/lib/ruby/gems/2.6.0/gems/guard-jekyll-plus-2.0.2/lib/guard/jekyll_plus/server.rb:68:in `fork'
	from /home/codio/anaconda/lib/ruby/gems/2.6.0/gems/guard-jekyll-plus-2.0.2/lib/guard/jekyll_plus/server.rb:68:in `start_jekyll'
	from /home/codio/anaconda/lib/ruby/gems/2.6.0/gems/guard-jekyll-plus-2.0.2/lib/guard/jekyll_plus/server.rb:18:in `start'
	from /home/codio/anaconda/lib/ruby/gems/2.6.0/gems/guard-jekyll-plus-2.0.2/lib/guard/jekyll_plus.rb:25:in `start'
	from /home/codio/anaconda/lib/ruby/gems/2.6.0/gems/guard-2.14.2/lib/guard/runner.rb:83:in `block (2 levels) in _supervise'
	from /home/codio/anaconda/lib/ruby/gems/2.6.0/gems/guard-2.14.2/lib/guard/ui/config.rb:62:in `block in with_progname'
	from /home/codio/anaconda/lib/ruby/gems/2.6.0/gems/lumberjack-1.0.13/lib/lumberjack/logger.rb:271:in `push_thread_local_value'
	from /home/codio/anaconda/lib/ruby/gems/2.6.0/gems/lumberjack-1.0.13/lib/lumberjack/logger.rb:232:in `set_progname'
	from /home/codio/anaconda/lib/ruby/gems/2.6.0/gems/guard-2.14.2/lib/guard/ui/config.rb:61:in `with_progname'
	from /home/codio/anaconda/lib/ruby/gems/2.6.0/gems/guard-2.14.2/lib/guard/runner.rb:81:in `block in _supervise'
	from /home/codio/anaconda/lib/ruby/gems/2.6.0/gems/guard-2.14.2/lib/guard/runner.rb:79:in `catch'
	from /home/codio/anaconda/lib/ruby/gems/2.6.0/gems/guard-2.14.2/lib/guard/runner.rb:79:in `_supervise'
	from /home/codio/anaconda/lib/ruby/gems/2.6.0/gems/guard-2.14.2/lib/guard/runner.rb:22:in `block (3 levels) in run'
	from /home/codio/anaconda/lib/ruby/gems/2.6.0/gems/guard-2.14.2/lib/guard/runner.rb:121:in `block (2 levels) in _run_group_plugins'
	from /home/codio/anaconda/lib/ruby/gems/2.6.0/gems/guard-2.14.2/lib/guard/runner.rb:119:in `each'
	from /home/codio/anaconda/lib/ruby/gems/2.6.0/gems/guard-2.14.2/lib/guard/runner.rb:119:in `block in _run_group_plugins'
	from /home/codio/anaconda/lib/ruby/gems/2.6.0/gems/guard-2.14.2/lib/guard/runner.rb:118:in `catch'
	from /home/codio/anaconda/lib/ruby/gems/2.6.0/gems/guard-2.14.2/lib/guard/runner.rb:118:in `_run_group_plugins'
	from /home/codio/anaconda/lib/ruby/gems/2.6.0/gems/guard-2.14.2/lib/guard/runner.rb:21:in `block (2 levels) in run'
	from /home/codio/anaconda/lib/ruby/gems/2.6.0/gems/guard-2.14.2/lib/guard/runner.rb:20:in `each'
	from /home/codio/anaconda/lib/ruby/gems/2.6.0/gems/guard-2.14.2/lib/guard/runner.rb:20:in `block in run'
	from /home/codio/anaconda/lib/ruby/gems/2.6.0/gems/lumberjack-1.0.13/lib/lumberjack.rb:34:in `unit_of_work'
	from /home/codio/anaconda/lib/ruby/gems/2.6.0/gems/guard-2.14.2/lib/guard/runner.rb:18:in `run'
	from /home/codio/anaconda/lib/ruby/gems/2.6.0/gems/guard-2.14.2/lib/guard/commander.rb:34:in `start'
	from /home/codio/anaconda/lib/ruby/gems/2.6.0/gems/guard-2.14.2/lib/guard/cli/environments/valid.rb:16:in `start_guard'
	from /home/codio/anaconda/lib/ruby/gems/2.6.0/gems/guard-2.14.2/lib/guard/cli.rb:122:in `start'
	from /home/codio/anaconda/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /home/codio/anaconda/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /home/codio/anaconda/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /home/codio/anaconda/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /home/codio/anaconda/lib/ruby/gems/2.6.0/gems/guard-2.14.2/lib/guard/aruba_adapter.rb:32:in `execute'
	from /home/codio/anaconda/lib/ruby/gems/2.6.0/gems/guard-2.14.2/lib/guard/aruba_adapter.rb:19:in `execute!'
	from /home/codio/anaconda/lib/ruby/gems/2.6.0/gems/guard-2.14.2/bin/_guard-core:11:in `<main>'
]2;

[0m15:09:04 - INFO - Bye bye...
bundle exec guard
Configuration file: _config.yml
18:58:05 - INFO - Jekyll [33mbuilding... [0m
18:58:06 - INFO - Jekyll [32mbuild completed in 0.82s [0m/home/codio/workspace/Introduction-to-Data-Science/IntroBook â†’ _site
18:58:06 - INFO - Jekyll watching and serving using jekyll at 0.0.0.0:4000/jupyter-book
18:58:06 - INFO - Jekyll watching
18:58:06 - INFO - LiveReload is waiting for a browser to connect.
18:58:06 - INFO - Guard is now watching at '/home/codio/workspace/Introduction-to-Data-Science/IntroBook'
[0G/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/guard-2.14.2/lib/guard/jobs/pry_wrapper.rb:279: warning: method Pry#input_array is deprecated. Use Pry#input_ring instead
[1] guard(main)> Error: Bad file descriptor - read
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:200:in `readline'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:200:in `block in input_readline'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/input_lock.rb:113:in `interruptible_region'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:199:in `input_readline'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:185:in `block in read_line'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:130:in `handle_read_errors'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:171:in `read_line'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:98:in `read'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:68:in `block in repl'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:67:in `loop'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:67:in `repl'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:38:in `block in start'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/input_lock.rb:59:in `__with_ownership'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/input_lock.rb:77:in `with_ownership'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:38:in `start'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:13:in `start'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/pry_class.rb:200:in `start'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/guard-2.14.2/lib/guard/jobs/pry_wrapper.rb:102:in `block (2 levels) in _switch_to_pry'
[1] guard(main)> Error: Bad file descriptor - read
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:200:in `readline'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:200:in `block in input_readline'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/input_lock.rb:113:in `interruptible_region'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:199:in `input_readline'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:185:in `block in read_line'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:130:in `handle_read_errors'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:171:in `read_line'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:98:in `read'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:68:in `block in repl'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:67:in `loop'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:67:in `repl'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:38:in `block in start'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/input_lock.rb:59:in `__with_ownership'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/input_lock.rb:77:in `with_ownership'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:38:in `start'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:13:in `start'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/pry_class.rb:200:in `start'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/guard-2.14.2/lib/guard/jobs/pry_wrapper.rb:102:in `block (2 levels) in _switch_to_pry'
[1] guard(main)> Error: Bad file descriptor - read
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:200:in `readline'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:200:in `block in input_readline'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/input_lock.rb:113:in `interruptible_region'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:199:in `input_readline'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:185:in `block in read_line'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:130:in `handle_read_errors'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:171:in `read_line'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:98:in `read'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:68:in `block in repl'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:67:in `loop'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:67:in `repl'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:38:in `block in start'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/input_lock.rb:59:in `__with_ownership'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/input_lock.rb:77:in `with_ownership'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:38:in `start'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:13:in `start'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/pry_class.rb:200:in `start'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/guard-2.14.2/lib/guard/jobs/pry_wrapper.rb:102:in `block (2 levels) in _switch_to_pry'
[1] guard(main)> Error: Bad file descriptor - read
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:200:in `readline'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:200:in `block in input_readline'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/input_lock.rb:113:in `interruptible_region'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:199:in `input_readline'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:185:in `block in read_line'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:130:in `handle_read_errors'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:171:in `read_line'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:98:in `read'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:68:in `block in repl'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:67:in `loop'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:67:in `repl'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:38:in `block in start'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/input_lock.rb:59:in `__with_ownership'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/input_lock.rb:77:in `with_ownership'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:38:in `start'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:13:in `start'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/pry_class.rb:200:in `start'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/guard-2.14.2/lib/guard/jobs/pry_wrapper.rb:102:in `block (2 levels) in _switch_to_pry'
[1] guard(main)> Error: Bad file descriptor - read
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:200:in `readline'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:200:in `block in input_readline'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/input_lock.rb:113:in `interruptible_region'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:199:in `input_readline'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:185:in `block in read_line'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:130:in `handle_read_errors'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:171:in `read_line'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:98:in `read'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:68:in `block in repl'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:67:in `loop'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:67:in `repl'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:38:in `block in start'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/input_lock.rb:59:in `__with_ownership'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/input_lock.rb:77:in `with_ownership'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:38:in `start'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:13:in `start'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/pry_class.rb:200:in `start'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/guard-2.14.2/lib/guard/jobs/pry_wrapper.rb:102:in `block (2 levels) in _switch_to_pry'
FATAL: Pry failed to get user input using `Readline`.
To fix this you may be able to pass input and output file descriptors to pry directly. e.g.
  Pry.config.input = STDIN
  Pry.config.output = STDOUT
  binding.pry

[0m    Server address: http://0.0.0.0:4000/jupyter-book/
  Server running... press ctrl-c to stop.
]2;

[0m18:58:06 - INFO - Bye bye...
bundle exec guard
Configuration file: _config.yml
19:01:06 - INFO - Jekyll [33mbuilding... [0m
19:01:07 - INFO - Jekyll [32mbuild completed in 0.81s [0m/home/codio/workspace/Introduction-to-Data-Science/IntroBook â†’ _site
19:01:07 - INFO - Jekyll watching and serving using jekyll at 0.0.0.0:4000/jupyter-book
19:01:07 - INFO - Jekyll watching
19:01:07 - INFO - LiveReload is waiting for a browser to connect.
19:01:07 - INFO - Guard is now watching at '/home/codio/workspace/Introduction-to-Data-Science/IntroBook'
[0G/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/guard-2.14.2/lib/guard/jobs/pry_wrapper.rb:279: warning: method Pry#input_array is deprecated. Use Pry#input_ring instead
[1] guard(main)> Error: Bad file descriptor - read
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:200:in `readline'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:200:in `block in input_readline'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/input_lock.rb:113:in `interruptible_region'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:199:in `input_readline'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:185:in `block in read_line'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:130:in `handle_read_errors'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:171:in `read_line'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:98:in `read'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:68:in `block in repl'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:67:in `loop'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:67:in `repl'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:38:in `block in start'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/input_lock.rb:59:in `__with_ownership'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/input_lock.rb:77:in `with_ownership'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:38:in `start'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:13:in `start'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/pry_class.rb:200:in `start'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/guard-2.14.2/lib/guard/jobs/pry_wrapper.rb:102:in `block (2 levels) in _switch_to_pry'
[1] guard(main)> Error: Bad file descriptor - read
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:200:in `readline'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:200:in `block in input_readline'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/input_lock.rb:113:in `interruptible_region'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:199:in `input_readline'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:185:in `block in read_line'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:130:in `handle_read_errors'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:171:in `read_line'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:98:in `read'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:68:in `block in repl'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:67:in `loop'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:67:in `repl'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:38:in `block in start'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/input_lock.rb:59:in `__with_ownership'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/input_lock.rb:77:in `with_ownership'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:38:in `start'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:13:in `start'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/pry_class.rb:200:in `start'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/guard-2.14.2/lib/guard/jobs/pry_wrapper.rb:102:in `block (2 levels) in _switch_to_pry'
[1] guard(main)> Error: Bad file descriptor - read
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:200:in `readline'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:200:in `block in input_readline'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/input_lock.rb:113:in `interruptible_region'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:199:in `input_readline'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:185:in `block in read_line'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:130:in `handle_read_errors'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:171:in `read_line'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:98:in `read'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:68:in `block in repl'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:67:in `loop'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:67:in `repl'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:38:in `block in start'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/input_lock.rb:59:in `__with_ownership'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/input_lock.rb:77:in `with_ownership'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:38:in `start'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:13:in `start'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/pry_class.rb:200:in `start'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/guard-2.14.2/lib/guard/jobs/pry_wrapper.rb:102:in `block (2 levels) in _switch_to_pry'
[1] guard(main)> Error: Bad file descriptor - read
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:200:in `readline'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:200:in `block in input_readline'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/input_lock.rb:113:in `interruptible_region'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:199:in `input_readline'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:185:in `block in read_line'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:130:in `handle_read_errors'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:171:in `read_line'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:98:in `read'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:68:in `block in repl'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:67:in `loop'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:67:in `repl'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:38:in `block in start'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/input_lock.rb:59:in `__with_ownership'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/input_lock.rb:77:in `with_ownership'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:38:in `start'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:13:in `start'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/pry_class.rb:200:in `start'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/guard-2.14.2/lib/guard/jobs/pry_wrapper.rb:102:in `block (2 levels) in _switch_to_pry'
[1] guard(main)> Error: Bad file descriptor - read
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:200:in `readline'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:200:in `block in input_readline'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/input_lock.rb:113:in `interruptible_region'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:199:in `input_readline'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:185:in `block in read_line'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:130:in `handle_read_errors'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:171:in `read_line'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:98:in `read'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:68:in `block in repl'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:67:in `loop'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:67:in `repl'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:38:in `block in start'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/input_lock.rb:59:in `__with_ownership'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/input_lock.rb:77:in `with_ownership'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:38:in `start'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:13:in `start'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/pry_class.rb:200:in `start'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/guard-2.14.2/lib/guard/jobs/pry_wrapper.rb:102:in `block (2 levels) in _switch_to_pry'
FATAL: Pry failed to get user input using `Readline`.
To fix this you may be able to pass input and output file descriptors to pry directly. e.g.
  Pry.config.input = STDIN
  Pry.config.output = STDOUT
  binding.pry

[0m    Server address: http://0.0.0.0:4000/jupyter-book/
  Server running... press ctrl-c to stop.
]2;

[0m19:01:07 - INFO - Bye bye...
bundle exec guard
Configuration file: _config.yml
23:06:19 - INFO - Jekyll [33mbuilding... [0m
23:06:21 - INFO - Jekyll [32mbuild completed in 1.67s [0m/home/codio/workspace/Introduction-to-Data-Science/IntroBook â†’ _site
23:06:21 - INFO - Jekyll watching and serving using jekyll at 0.0.0.0:4000/jupyter-book
23:06:21 - INFO - Jekyll watching
23:06:21 - INFO - LiveReload is waiting for a browser to connect.
23:06:21 - INFO - Guard is now watching at '/home/codio/workspace/Introduction-to-Data-Science/IntroBook'
[0G/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/guard-2.14.2/lib/guard/jobs/pry_wrapper.rb:279: warning: method Pry#input_array is deprecated. Use Pry#input_ring instead
[1] guard(main)> Error: Bad file descriptor - read
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:200:in `readline'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:200:in `block in input_readline'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/input_lock.rb:113:in `interruptible_region'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:199:in `input_readline'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:185:in `block in read_line'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:130:in `handle_read_errors'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:171:in `read_line'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:98:in `read'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:68:in `block in repl'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:67:in `loop'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:67:in `repl'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:38:in `block in start'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/input_lock.rb:59:in `__with_ownership'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/input_lock.rb:77:in `with_ownership'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:38:in `start'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:13:in `start'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/pry_class.rb:200:in `start'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/guard-2.14.2/lib/guard/jobs/pry_wrapper.rb:102:in `block (2 levels) in _switch_to_pry'
[1] guard(main)> Error: Bad file descriptor - read
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:200:in `readline'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:200:in `block in input_readline'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/input_lock.rb:113:in `interruptible_region'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:199:in `input_readline'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:185:in `block in read_line'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:130:in `handle_read_errors'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:171:in `read_line'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:98:in `read'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:68:in `block in repl'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:67:in `loop'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:67:in `repl'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:38:in `block in start'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/input_lock.rb:59:in `__with_ownership'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/input_lock.rb:77:in `with_ownership'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:38:in `start'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:13:in `start'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/pry_class.rb:200:in `start'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/guard-2.14.2/lib/guard/jobs/pry_wrapper.rb:102:in `block (2 levels) in _switch_to_pry'
[1] guard(main)> Error: Bad file descriptor - read
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:200:in `readline'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:200:in `block in input_readline'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/input_lock.rb:113:in `interruptible_region'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:199:in `input_readline'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:185:in `block in read_line'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:130:in `handle_read_errors'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:171:in `read_line'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:98:in `read'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:68:in `block in repl'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:67:in `loop'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:67:in `repl'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:38:in `block in start'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/input_lock.rb:59:in `__with_ownership'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/input_lock.rb:77:in `with_ownership'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:38:in `start'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:13:in `start'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/pry_class.rb:200:in `start'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/guard-2.14.2/lib/guard/jobs/pry_wrapper.rb:102:in `block (2 levels) in _switch_to_pry'
[1] guard(main)> Error: Bad file descriptor - read
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:200:in `readline'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:200:in `block in input_readline'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/input_lock.rb:113:in `interruptible_region'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:199:in `input_readline'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:185:in `block in read_line'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:130:in `handle_read_errors'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:171:in `read_line'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:98:in `read'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:68:in `block in repl'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:67:in `loop'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:67:in `repl'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:38:in `block in start'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/input_lock.rb:59:in `__with_ownership'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/input_lock.rb:77:in `with_ownership'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:38:in `start'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:13:in `start'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/pry_class.rb:200:in `start'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/guard-2.14.2/lib/guard/jobs/pry_wrapper.rb:102:in `block (2 levels) in _switch_to_pry'
[1] guard(main)> Error: Bad file descriptor - read
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:200:in `readline'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:200:in `block in input_readline'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/input_lock.rb:113:in `interruptible_region'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:199:in `input_readline'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:185:in `block in read_line'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:130:in `handle_read_errors'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:171:in `read_line'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:98:in `read'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:68:in `block in repl'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:67:in `loop'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:67:in `repl'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:38:in `block in start'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/input_lock.rb:59:in `__with_ownership'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/input_lock.rb:77:in `with_ownership'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:38:in `start'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/repl.rb:13:in `start'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/pry_class.rb:200:in `start'
/home/codio/anaconda/lib/ruby/gems/2.6.0/gems/guard-2.14.2/lib/guard/jobs/pry_wrapper.rb:102:in `block (2 levels) in _switch_to_pry'
FATAL: Pry failed to get user input using `Readline`.
To fix this you may be able to pass input and output file descriptors to pry directly. e.g.
  Pry.config.input = STDIN
  Pry.config.output = STDOUT
  binding.pry

[0m    Server address: http://0.0.0.0:4000/jupyter-book/
  Server running... press ctrl-c to stop.
]2;

[0m23:06:21 - INFO - Bye bye...
